### ISSUE TITLE
Error loading on a Paper 1.19.2 bungeecord server | java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig

### ISSUE THREAD

**Issue by santiramirezc** [PedroJM96/PixelLogin#1]
Hola! 

Tengo problemas para iniciar este plugin en mi proxy server. Estoy usando la última versión Paper 1.19.2 al dia de hoy junto con WorldEdit y WorldGuard. Ya configuré el plugin para que use una base de datos mysql, pero parece que este error es más a nivel del código :/ 
Este es mi Log: 

Hello!

I am having trouble starting this plugin on my proxy server. I am using the latest version of Paper 1.19.2 as of today along with WorldEdit and WorldGuard. I already configured the plugin to use a mysql database, but it seems that this error is more at the code level :/
This is my log:

```
[Geyser-BungeeCord] ******************************************
18:47:36 [INFO] [Geyser-BungeeCord]
18:47:36 [INFO] [Geyser-BungeeCord] Loading Geyser version 2.0.7-SNAPSHOT (git-master-8dde4b4)
18:47:36 [INFO] [Geyser-BungeeCord]
18:47:36 [INFO] [Geyser-BungeeCord] ******************************************
18:47:37 [INFO] [Geyser-BungeeCord] Started Geyser on 0.0.0.0:19132
18:47:37 [INFO] [Geyser-BungeeCord] Done (1,811s)! Run /geyser help for help!
18:47:37 [INFO] Enabled plugin Geyser-BungeeCord version 2.0.7-SNAPSHOT by GeyserMC
18:47:37 [INFO] Enabled plugin reconnect_yaml version git:reconnect_yaml:1.19-R0.1-SNAPSHOT:5e7dcc4:1660 by SpigotMC
18:47:37 [INFO] Enabled plugin cmd_find version git:cmd_find:1.19-R0.1-SNAPSHOT:5e7dcc4:1660 by SpigotMC
18:47:37 [INFO] -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
18:47:37 [INFO] -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
18:47:37 [INFO] [PixelLogin] Plugin Create by PedroJM96.
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:37 [INFO] [PixelLogin] Loading Libraries...
18:47:38 [INFO] [PixelLogin] Register commands...
18:47:38 [INFO] [PixelLogin] Register command /register
18:47:38 [INFO] [PixelLogin] Register command /login
18:47:38 [INFO] [PixelLogin] Register command /unregister
18:47:38 [INFO] [PixelLogin] Register command /changepassword
18:47:38 [INFO] [PixelLogin] Register command /pixellogin
18:47:38 [INFO] [PixelLogin] Register sub-command /pixellogin register
18:47:38 [INFO] [PixelLogin] Register sub-command /pixellogin cracked
18:47:38 [INFO] [PixelLogin] Register sub-command /pixellogin premium
18:47:38 [INFO] [PixelLogin] Register sub-command /pixellogin info
18:47:38 [INFO] [PixelLogin] Register sub-command /pixellogin accounts
18:47:38 [INFO] [PixelLogin] Register sub-command /pixellogin unregister
18:47:38 [INFO] [PixelLogin] Register sub-command /pixellogin help
18:47:38 [INFO] [PixelLogin] Loading configuration...
18:47:38 [INFO] [PixelLogin] Load config.yml
18:47:38 [INFO] [PixelLogin] config.yml loaded.
18:47:38 [INFO] [PixelLogin] Load messages_EN.yml
18:47:38 [INFO] [PixelLogin] messages_EN.yml loaded.
18:47:38 [INFO] [PixelLogin] Data set to MySQL
18:47:38 [WARNING] Exception encountered when loading plugin: PixelLogin
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariConfig
    at com.pedrojm96.pixellogin.bukkit.bungee.data.CoreMySQL.<init>(CoreMySQL.java:66)
    at com.pedrojm96.pixellogin.bungee.PixelLoginBungee.onEnable(PixelLoginBungee.java:202)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:265)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:285)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariConfig
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
    ... 6 more
```

**Comment by PedroJM96** [comment]
Hola gracias por reportar ese error ya estoy trabajando en la actualizacion.

Hi, thanks for reporting that bug. I'm already working on the update.

**Comment by PedroJM96** [comment]
Fixed reported bugs.
