### ISSUE TITLE
/pin not working

### ISSUE THREAD

**Issue by ErzenXz** [PedroJM96/PixelLogin#10]
[00:55:38 INFO]: ErzenPvP issued server command: /pin
[00:55:38 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'pin' in plugin PixelLoginBukkit v2.1.6
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:146) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.dispatchCommand(CraftServer.java:666) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.handleCommand(PlayerConnection.java:1189) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java:1001) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:45) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PacketPlayInChat.a(PacketPlayInChat.java:1) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:13) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_312]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_312]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:774) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:378) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:713) [patched_1.8.8.jar:git-PaperSpigot-445]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:616) [patched_1.8.8.jar:git-PaperSpigot-445]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_312]
Caused by: java.lang.NullPointerException
        at com.pedrojm96.pixellogin.CoreMaterial.createItem(CoreMaterial.java:1001) ~[?:?]
        at com.pedrojm96.pixellogin.bukkit.SimpleGUI.update(SimpleGUI.java:99) ~[?:?]
        at com.pedrojm96.pixellogin.bukkit.SimpleGUI.open(SimpleGUI.java:90) ~[?:?]
        at com.pedrojm96.pixellogin.bukkit.CommandsPin.onCommand(CommandsPin.java:56) ~[?:?]
        at com.pedrojm96.pixellogin.command.CorePluginCommand.onCommand(CorePluginCommand.java:118) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.8.8.jar:git-PaperSpigot-445]
        ... 15 more

I keep getting this error, also the red An error occured while ... error shows up.

**Comment by ErzenXz** [comment]
I had to disable pin on staff to allow me to join my server!

**Comment by PedroJM96** [comment]
Fixed in next version
