### ISSUE TITLE
Error when connecting to 1.19.2 Waterfall. 

### ISSUE THREAD

**Issue by Feraldragon** [PedroJM96/PixelLogin#2]
```
[PixelLoginBukkit] [STDOUT] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
[22:38:53 WARN]: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredClasses()" because the return value of "com.pedrojm96.pixellogin.CoreReflection.getNMSClass(String)" is null
[22:38:53 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.effect.CoreTitles.send(CoreTitles.java:72)
[22:38:53 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.effect.CoreTitles.sendTitles(CoreTitles.java:36)
[22:38:53 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.bukkit.ChannelController$6.run(ChannelController.java:388)
[22:38:53 WARN]: at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:38:53 WARN]: at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:38:53 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1493)
[22:38:53 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[22:38:53 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1417)
[22:38:53 WARN]: at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1193)
[22:38:53 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[22:38:53 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
[22:38:58 INFO]: [PixelLoginBukkit] [STDOUT] Please report the bug at: https://github.com/PedroJM96/CoreLibBukkit
[22:38:58 WARN]: java.lang.ClassNotFoundException: net.minecraft.server.v1_19_R1.IChatBaseComponent
[22:38:58 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151)
[22:38:58 WARN]: at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103)
[22:38:58 WARN]: at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[22:38:58 WARN]: at java.base/java.lang.Class.forName0(Native Method)
[22:38:58 WARN]: at java.base/java.lang.Class.forName(Class.java:375)
[22:38:58 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.CoreReflection.getClass(CoreReflection.java:305)
[22:38:58 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.CoreReflection.getNMSClass(CoreReflection.java:27)
[22:38:58 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.effect.CoreTitles.send(CoreTitles.java:72)
[22:38:58 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.effect.CoreTitles.sendTitles(CoreTitles.java:36)
[22:38:58 WARN]: at PixelLogin-2.0.9-shaded.jar//com.pedrojm96.pixellogin.bukkit.ChannelController$6.run(ChannelController.java:388)
[22:38:58 WARN]: at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[22:38:58 WARN]: at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[22:38:58 WARN]: at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1493)
[22:38:58 WARN]: at net.minecraft.server.dedicated.DedicatedServer.b(DedicatedServer.java:446)
[22:38:58 WARN]: at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:1417)
[22:38:58 WARN]: at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1193)
[22:38:58 WARN]: at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[22:38:58 WARN]: at java.base/java.lang.Thread.run(Thread.java:833)
```
Hope it's correct place where to get support.

using Pixellogin lastest version from spigot website.

**Comment by PedroJM96** [comment]
Are you using Waterfall or PaperMC?

**Comment by Feraldragon** [comment]
Pixellogin plugin is on waterfall & and survival and hub are papermc and have plugin also for titles and stuff.

**Comment by PedroJM96** [comment]
what version of papermc are you using?

Ing. Pedro Martínez.

Soyuz Ingeniería C.A.

**Comment by Feraldragon** [comment]
1.19.2 Lastest 135

**Comment by Feraldragon** [comment]
Also, when i write /register command it tells me that i dont have permisson, but i have * permissions.

**Comment by PedroJM96** [comment]
The bugs in the latest version are already fixed.
