### ISSUE TITLE
Lastest waterfall version.

### ISSUE THREAD

**Issue by Feraldragon** [PedroJM96/PixelLogin#3]
```
[20:22:33 INFO]: -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[20:22:33 INFO]:   _____ _          _ _                 _       
[20:22:33 INFO]:  |  __ (_)        | | |               (_)      
[20:22:33 INFO]:  | |__) |__  _____| | |     ___   __ _ _ _ __  
[20:22:33 INFO]:  |  ___/ \ \/ / _ \ | |    / _ \ / _` | | '_ \
[20:22:33 INFO]:  | |   | |›  ‹  __/ | |___| (_) | (_| | | | | |
[20:22:33 INFO]:  |_|   |_/_/\_\___|_|______\___/ \__, |_|_| |_|
[20:22:33 INFO]:                                   __/ |        
[20:22:33 INFO]:                                  |___/         
[20:22:33 INFO]: -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
[20:22:33 INFO]: [PixelLogin] Plugin Create by PedroJM96.
[20:22:33 INFO]: [PixelLogin] Register commands...
[20:22:33 INFO]: [PixelLogin] Register command /register
[20:22:33 INFO]: [PixelLogin] Register command /login
[20:22:33 INFO]: [PixelLogin] Register command /unregister
[20:22:33 INFO]: [PixelLogin] Register command /changepassword
[20:22:33 INFO]: [PixelLogin] Register command /pixellogin
[20:22:33 INFO]: [PixelLogin] Register sub-command /pixellogin register
[20:22:33 INFO]: [PixelLogin] Register sub-command /pixellogin cracked
[20:22:33 INFO]: [PixelLogin] Register sub-command /pixellogin premium
[20:22:33 INFO]: [PixelLogin] Register sub-command /pixellogin info
[20:22:33 INFO]: [PixelLogin] Register sub-command /pixellogin accounts
[20:22:33 INFO]: [PixelLogin] Register sub-command /pixellogin unregister
[20:22:33 INFO]: [PixelLogin] Register sub-command /pixellogin help
[20:22:33 INFO]: [PixelLogin] Loading configuration...
[20:22:33 INFO]: [PixelLogin] Load config.yml
[20:22:33 INFO]: [PixelLogin] config.yml loaded.
[20:22:33 INFO]: [PixelLogin] Load messages_EN.yml
[20:22:33 INFO]: [PixelLogin] messages_EN.yml loaded.
[20:22:33 INFO]: [PixelLogin] Data set to MySQL
[20:22:33 ERROR]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[20:22:33 ERROR]: [main] INFO com.pedrojm96.pixellogin.libs.com.zaxxer.hikari.HikariDataSource - PixelLoginMySQLPool - Starting...
[20:22:33 ERROR]: [main] WARN com.pedrojm96.pixellogin.libs.com.zaxxer.hikari.util.DriverDataSource - Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
[20:22:33 INFO] [NetworkTools]: Connected to database!
[20:22:33 ERROR]: [main] INFO com.pedrojm96.pixellogin.libs.com.zaxxer.hikari.HikariDataSource - PixelLoginMySQLPool - Start completed.
[20:22:33 INFO]: [PixelLogin] Loaded database
[20:22:33 INFO]: [PixelLogin] [id,int] [uuid,varchar] [name,varchar] [ip,varchar] [password,varchar] [pincode,varchar] [premium,int] [registered,int] [login,int] [pin_login,int] [token,varchar] [first_login,bigint] [last_login,bigint] [last_disconnected,bigint] [hash,varchar] 
[20:22:33 INFO]: Checking for updates...
[20:22:33 WARN]: Exception encountered when loading plugin: PixelLogin
java.lang.NullPointerException: owner
at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:907) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:94) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.scheduler.BungeeScheduler.schedule(BungeeScheduler.java:88) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.scheduler.BungeeScheduler.runAsync(BungeeScheduler.java:82) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at com.pedrojm96.pixellogin.bungee.PixelLoginBungee.checkForUpdates(PixelLoginBungee.java:147) ~[?:?]
at com.pedrojm96.pixellogin.bungee.PixelLoginBungee.onEnable(PixelLoginBungee.java:131) ~[?:?]
at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:315) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.BungeeCord.start(BungeeCord.java:290) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
```

This picture is taken from waterfall console

On papermc everything is ok  database connects sucessfully and no errors occured.

**Comment by Feraldragon** [comment]
Player's can connect to server, 
![image](https://user-images.githubusercontent.com/75722852/187976191-a345fd4c-ceb9-4eff-9ded-607f4b24fb8b.png)

**Comment by PedroJM96** [comment]
> Player's can connect to server, ![image](https://user-images.githubusercontent.com/75722852/187976191-a345fd4c-ceb9-4eff-9ded-607f4b24fb8b.png)
Make sure the permissions are set on the waterfall server. You should have to manage the permissions on the waterfall and papermc servers, I recommend a permissions plugin that synchronizes the papermc servers with the waterfall server.

**Comment by Feraldragon** [comment]
i have luckperms plugin & all the permissions are synced cross every server
, i have given all permissions to myshelf.

**Comment by PedroJM96** [comment]
Try manually adding the permission "pixellogin.player.register"

**Comment by Feraldragon** [comment]
Ah yes when i do add all permissons manually everything works.
just the error occurs still, but no problem it dont spam
