### ISSUE TITLE
Error on waterfall 1.19.2

### ISSUE THREAD

**Issue by Feraldragon** [PedroJM96/PixelLogin#5]
```
Error dispatching event PluginMessageEvent(super=TargetedEvent(sender=net.md_5.bungee.ServerConnection@5f873ee9, receiver=987296097712), cancelled=false, tag=pixellogin:update) to listener com.pedrojm96.pixellogin.bungee.PixelPluginMSGListener@2c56eba5
java.lang.NullPointerException: Cannot invoke "com.pedrojm96.pixellogin.bungee.ProxiedProfile.isRegistered()" because "plogin" is null
at com.pedrojm96.pixellogin.bungee.ChannelController.onGetProfile(ChannelController.java:175) ~[?:?]
at com.pedrojm96.pixellogin.bungee.PixelPluginMSGListener.onPluginMessage(PixelPluginMSGListener.java:45) ~[?:?]
at jdk.internal.reflect.GeneratedMethodAccessor18.invoke(Unknown Source) ~[?:?]
at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.event.EventBus.post(EventBus.java:50) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:466) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.connection.DownstreamBridge.handle(DownstreamBridge.java:289) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.protocol.packet.PluginMessage.handle(PluginMessage.java:93) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:114) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:336) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:308) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:499) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.19-504.jar:git:Waterfall-Bootstrap:1.19-R0.1-SNAPSHOT:5c1e956:504]
at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

Lastest updated pixellogin version.
Minecraft version 1.19.2. 

This error is spamming my console every s when bots trying to join my server.

**Comment by PedroJM96** [comment]
Fixed in the next version.
